baseURL = "https://www.turbotides.com"
canonifyURLs = false
title = "TURBOTIDES"
author = "Taize Technology"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

[markup]
  goldmark = { renderer = { unsafe = true } }

[params]
  showBlog = true
  mainSections = ['blog']
  googleFonts = true

  [params.logo]
    main = "img/logo/tt_logo.png"
    alt = "TurboTides Logo"
    size = "h-16"

  [params.site]
    name = "TURBOTIDES"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true
    material = true

  [params.homepage_meta_tags]
    meta_description = "TurboTides - Professional CAE industrial software solution to assist enterprises in efficient simulation and optimization design"
    meta_og_title = "TurboTides"
    meta_og_type = "website"
    meta_og_url = "https://www.turbotides.com/"
    meta_og_image = "https://www.turbotides.com/img/tn.png"
    meta_og_description = "TurboTides provides efficient CAE simulation and optimization software to help enterprises improve design efficiency"

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "HOME"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "software"
    name = "SOFTWARE"
    url = "/software/"
    weight = 2

  [[menu.main]]
    identifier = "services"
    name = "SERVICES"
    url = "/services/"
    weight = 3

  [[menu.main]]
    identifier = "news"
    name = "BLOGS"
    url = "/news/"
    weight = 4

  [[menu.main]]
    identifier = "software-cases"
    name = "SOFTWARE CASES"
    url = "/softwarecases/"
    weight = 5

  [[menu.main]]
    identifier = "other-software"
    name = "OTHER SOFTWARE"
    url = ""
    weight = 6

  [[menu.main]]
    identifier = "products"
    parent = "other-software"
    name = "Products"
    url = "/other-software/products/"
    weight = 61

  [[menu.main]]
    identifier = "other-cases"
    parent = "other-software"
    name = "Other Cases"
    url = "/other-software/cases/"
    weight = 62

  [[menu.main]]
    identifier = "contact"
    name = "CONTACT US"
    url = "/contact/"
    weight = 7

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Return"
    url = "/"
    pre = "<i class='fas fa-home text-2xl'></i>"
      weight = 2
